# Generated by Django 6.0.6 on 2026-09-03 07:28

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow_agent', '0001_initial'),
        ('workflow_orchestrator', '0002_remove_ai_models'),
        migrations.swappable_dependency(settings.TASK_CREDENTIAL_MODEL),
        migrations.swappable_dependency(settings.TASK_ORGANIZATION_MODEL),
        migrations.swappable_dependency(settings.TASK_RESOURCE_MODEL),
        migrations.swappable_dependency(settings.TASK_SERVICE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('source', models.TextField(help_text='Python function source code')),
                ('source_hash', models.CharField(help_text='SHA256 hash of source code', max_length=64, unique=True)),
                ('signature', models.JSONField(blank=True, default=dict, help_text='Function parameters and return types')),
                ('is_approved', models.BooleanField(default=False, help_text='Human approval required for execution')),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='JinjaHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Function name in Jinja globals', max_length=100, unique=True)),
                ('source', models.TextField(help_text='Python function source code')),
                ('source_hash', models.CharField(help_text='SHA256 hash of source code', max_length=64, unique=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Human approval required for execution')),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='User input or instruction')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('awaiting_input', 'Awaiting Input'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='planning', max_length=30)),
                ('plan_json', models.JSONField(blank=True, default=dict, help_text='Proposed workflow plan in declarative JSON format')),
                ('model', models.CharField(blank=True, help_text='Resolved primary AI model ID used for planning', max_length=100)),
                ('iteration_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(help_text='Organization requesting agent run', on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to=settings.TASK_ORGANIZATION_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Instruction for human task')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=20)),
                ('result_input', models.JSONField(blank=True, default=dict, help_text='Data provided by human upon completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_steps', to='workflow_agent.agentrun')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_steps', to=settings.TASK_ORGANIZATION_MODEL)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_steps', to='workflow_orchestrator.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool Result'), ('summary', 'Summary')], max_length=20)),
                ('tool_name', models.CharField(blank=True, max_length=100)),
                ('tool_args', models.JSONField(blank=True, default=dict)),
                ('content', models.TextField(blank=True)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('sequence', models.PositiveIntegerField()),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workflow_agent.agentrun')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['agent_run', 'sequence'], name='workflow_ag_agent_r_fd5931_idx')],
            },
        ),
        migrations.CreateModel(
            name='AiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.CharField(max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('user_prompt', models.TextField(blank=True)),
                ('response_size_chars', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_billable', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='workflow_agent.agentrun')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_ai_usage_logs', to=settings.TASK_CREDENTIAL_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_ai_usage_logs', to=settings.TASK_ORGANIZATION_MODEL)),
                ('service', models.ForeignKey(help_text='AI Provider Service', on_delete=django.db.models.deletion.CASCADE, related_name='agent_ai_usage_logs', to=settings.TASK_SERVICE_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', 'timestamp'], name='workflow_ag_organiz_54d146_idx'), models.Index(fields=['service', 'timestamp'], name='workflow_ag_service_e25d80_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApiDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('doc_type', models.CharField(choices=[('openapi', 'OpenAPI 3.x'), ('swagger', 'Swagger 2.0'), ('html', 'HTML Documentation'), ('markdown', 'Markdown'), ('yaml', 'YAML'), ('json', 'JSON'), ('text', 'Plain Text')], default='openapi', max_length=20)),
                ('doc_source', models.CharField(choices=[('manual', 'Manual Upload'), ('web_fetch', 'Web Fetch')], default='manual', max_length=20)),
                ('verified', models.BooleanField(default=False, help_text='Human verified against vendor docs')),
                ('source_url', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('content_gcs_url', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('service', models.ForeignKey(help_text='Service this documentation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='agent_api_docs', to=settings.TASK_SERVICE_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('service', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ModelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasoning_tier', models.CharField(choices=[('plan', 'Planning'), ('supervise', 'Supervision'), ('extract', 'Data Extraction'), ('transform', 'Transformation'), ('summarize', 'Summarization')], max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_preferences', to=settings.TASK_ORGANIZATION_MODEL)),
                ('resource', models.ForeignKey(help_text='Model Resource record in workflow_orchestrator', on_delete=django.db.models.deletion.CASCADE, related_name='model_preferences', to=settings.TASK_RESOURCE_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'reasoning_tier')},
            },
        ),
    ]
