from django.conf import settings
from django.db import models

try:
    from pgvector.django import VectorField
    _HAS_PGVECTOR = True
except ImportError:
    _HAS_PGVECTOR = False

_ORGANIZATION_MODEL = getattr(settings, 'TASK_ORGANIZATION_MODEL', 'workflow_orchestrator.Organization')
_CREDENTIAL_MODEL = getattr(settings, 'TASK_CREDENTIAL_MODEL', 'workflow_orchestrator.Credential')
_SERVICE_MODEL = getattr(settings, 'TASK_SERVICE_MODEL', 'workflow_orchestrator.Service')
_RESOURCE_MODEL = getattr(settings, 'TASK_RESOURCE_MODEL', 'workflow_orchestrator.Resource')


class AgentRun(models.Model):
    """
    Tracks an agent's planning run.
    """
    STATUS_PLANNING = 'planning'
    STATUS_AWAITING_INPUT = 'awaiting_input'
    STATUS_SUCCEEDED = 'succeeded'
    STATUS_FAILED = 'failed'

    STATUS_CHOICES = [
        (STATUS_PLANNING, 'Planning'),
        (STATUS_AWAITING_INPUT, 'Awaiting Input'),
        (STATUS_SUCCEEDED, 'Succeeded'),
        (STATUS_FAILED, 'Failed'),
    ]

    organization = models.ForeignKey(
        _ORGANIZATION_MODEL,
        on_delete=models.CASCADE,
        related_name='agent_runs',
        help_text="Organization requesting agent run"
    )
    prompt = models.TextField(help_text="User input or instruction")
    status = models.CharField(
        max_length=30,
        choices=STATUS_CHOICES,
        default=STATUS_PLANNING
    )
    plan_json = models.JSONField(
        default=dict,
        blank=True,
        help_text="Proposed workflow plan in declarative JSON format"
    )
    model = models.CharField(
        max_length=100,
        blank=True,
        help_text="Resolved primary AI model ID used for planning"
    )
    iteration_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"AgentRun {self.id}: {self.status} ({self.organization})"


class AgentMessage(models.Model):
    """
    Append-only transcript message for an AgentRun.
    """
    ROLE_USER = 'user'
    ROLE_ASSISTANT = 'assistant'
    ROLE_TOOL = 'tool'
    ROLE_SUMMARY = 'summary'

    ROLE_CHOICES = [
        (ROLE_USER, 'User'),
        (ROLE_ASSISTANT, 'Assistant'),
        (ROLE_TOOL, 'Tool Result'),
        (ROLE_SUMMARY, 'Summary'),
    ]

    agent_run = models.ForeignKey(
        AgentRun,
        on_delete=models.CASCADE,
        related_name='messages'
    )
    role = models.CharField(max_length=20, choices=ROLE_CHOICES)
    tool_name = models.CharField(max_length=100, blank=True)
    tool_args = models.JSONField(default=dict, blank=True)
    content = models.TextField(blank=True)
    token_usage = models.JSONField(default=dict, blank=True)
    sequence = models.PositiveIntegerField()

    class Meta:
        ordering = ['sequence']
        indexes = [
            models.Index(fields=['agent_run', 'sequence']),
        ]

    def __str__(self):
        return f"Message {self.sequence} for Run {self.agent_run_id} ({self.role})"


class JinjaHelper(models.Model):
    """
    DB-stored Jinja2 helper functions created or used by the agent.
    Must be approved before being loaded into Jinja environment.
    """
    name = models.CharField(max_length=100, unique=True, help_text="Function name in Jinja globals")
    source = models.TextField(help_text="Python function source code")
    source_hash = models.CharField(max_length=64, unique=True, help_text="SHA256 hash of source code")
    is_approved = models.BooleanField(default=False, help_text="Human approval required for execution")
    version = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return f"JinjaHelper: {self.name} (v{self.version}, approved={self.is_approved})"


class GeneratedFunction(models.Model):
    """
    DB-stored Python functions generated by the agent for custom python tasks.
    """
    slug = models.SlugField(max_length=120, unique=True)
    source = models.TextField(help_text="Python function source code")
    source_hash = models.CharField(max_length=64, unique=True, help_text="SHA256 hash of source code")
    signature = models.JSONField(default=dict, blank=True, help_text="Function parameters and return types")
    is_approved = models.BooleanField(default=False, help_text="Human approval required for execution")
    version = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['slug']

    def __str__(self):
        return f"GeneratedFunction: {self.slug} (v{self.version}, approved={self.is_approved})"


class ManualStep(models.Model):
    """
    Durable manual task / TODO step for human-in-the-loop workflows.
    """
    STATUS_PENDING = 'pending'
    STATUS_DONE = 'done'

    STATUS_CHOICES = [
        (STATUS_PENDING, 'Pending'),
        (STATUS_DONE, 'Done'),
    ]

    organization = models.ForeignKey(
        _ORGANIZATION_MODEL,
        on_delete=models.CASCADE,
        related_name='manual_steps'
    )
    agent_run = models.ForeignKey(
        AgentRun,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='manual_steps'
    )
    workflow = models.ForeignKey(
        'workflow_orchestrator.Workflow',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='manual_steps'
    )
    description = models.TextField(help_text="Instruction for human task")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=STATUS_PENDING)
    result_input = models.JSONField(default=dict, blank=True, help_text="Data provided by human upon completion")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"ManualStep {self.id}: {self.status} for {self.organization}"


class ModelPreference(models.Model):
    """
    Per-organization AI model selection per reasoning tier.
    """
    REASONING_TIER_CHOICES = [
        ('plan', 'Planning'),
        ('supervise', 'Supervision'),
        ('extract', 'Data Extraction'),
        ('transform', 'Transformation'),
        ('summarize', 'Summarization'),
    ]

    organization = models.ForeignKey(
        _ORGANIZATION_MODEL,
        on_delete=models.CASCADE,
        related_name='model_preferences'
    )
    reasoning_tier = models.CharField(max_length=50, choices=REASONING_TIER_CHOICES)
    resource = models.ForeignKey(
        _RESOURCE_MODEL,
        on_delete=models.CASCADE,
        related_name='model_preferences',
        help_text="Model Resource record in workflow_orchestrator"
    )

    class Meta:
        unique_together = ('organization', 'reasoning_tier')

    def __str__(self):
        return f"{self.organization} - {self.reasoning_tier} -> {self.resource}"


class ApiDocumentation(models.Model):
    """
    Store API documentation for retrieval and planning.
    Supports OpenAPI, Swagger, Markdown, and web-fetched docs.
    """
    DOC_TYPE_OPENAPI = 'openapi'
    DOC_TYPE_SWAGGER = 'swagger'
    DOC_TYPE_HTML = 'html'
    DOC_TYPE_MARKDOWN = 'markdown'
    DOC_TYPE_YAML = 'yaml'
    DOC_TYPE_JSON = 'json'
    DOC_TYPE_TEXT = 'text'

    DOC_TYPE_CHOICES = [
        (DOC_TYPE_OPENAPI, 'OpenAPI 3.x'),
        (DOC_TYPE_SWAGGER, 'Swagger 2.0'),
        (DOC_TYPE_HTML, 'HTML Documentation'),
        (DOC_TYPE_MARKDOWN, 'Markdown'),
        (DOC_TYPE_YAML, 'YAML'),
        (DOC_TYPE_JSON, 'JSON'),
        (DOC_TYPE_TEXT, 'Plain Text'),
    ]

    DOC_SOURCE_MANUAL = 'manual'
    DOC_SOURCE_WEB_FETCH = 'web_fetch'

    DOC_SOURCE_CHOICES = [
        (DOC_SOURCE_MANUAL, 'Manual Upload'),
        (DOC_SOURCE_WEB_FETCH, 'Web Fetch'),
    ]

    STATUS_PENDING = 'pending'
    STATUS_PROCESSING = 'processing'
    STATUS_PROCESSED = 'processed'
    STATUS_FAILED = 'failed'

    STATUS_CHOICES = [
        (STATUS_PENDING, 'Pending'),
        (STATUS_PROCESSING, 'Processing'),
        (STATUS_PROCESSED, 'Processed'),
        (STATUS_FAILED, 'Failed'),
    ]

    service = models.ForeignKey(
        _SERVICE_MODEL,
        on_delete=models.CASCADE,
        related_name='agent_api_docs',
        help_text="Service this documentation belongs to"
    )
    name = models.CharField(max_length=200)
    version = models.CharField(max_length=50, blank=True)
    doc_type = models.CharField(max_length=20, choices=DOC_TYPE_CHOICES, default=DOC_TYPE_OPENAPI)
    doc_source = models.CharField(max_length=20, choices=DOC_SOURCE_CHOICES, default=DOC_SOURCE_MANUAL)
    verified = models.BooleanField(default=False, help_text="Human verified against vendor docs")
    source_url = models.TextField(blank=True, null=True)
    content = models.TextField(blank=True)
    content_gcs_url = models.CharField(max_length=500, blank=True)
    metadata = models.JSONField(default=dict, blank=True)
    processing_status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=STATUS_PENDING)
    processing_error = models.TextField(blank=True, null=True)
    is_latest = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    processed_at = models.DateTimeField(null=True, blank=True)

    if _HAS_PGVECTOR:
        embedding = VectorField(dimensions=1536, null=True, blank=True)
    else:
        embedding = models.JSONField(null=True, blank=True, help_text="Embedding vector fallback (JSON)")

    class Meta:
        ordering = ['-created_at']
        unique_together = [('service', 'version')]

    def __str__(self):
        return f"{self.service.name} Agent Docs ({self.version or 'latest'})"


class AiUsageLog(models.Model):
    """
    Log of AI API usage (token consumption) for billing and analytics.
    """
    organization = models.ForeignKey(
        _ORGANIZATION_MODEL,
        on_delete=models.CASCADE,
        related_name='agent_ai_usage_logs'
    )
    service = models.ForeignKey(
        _SERVICE_MODEL,
        on_delete=models.CASCADE,
        related_name='agent_ai_usage_logs',
        help_text="AI Provider Service"
    )
    credential = models.ForeignKey(
        _CREDENTIAL_MODEL,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='agent_ai_usage_logs'
    )
    agent_run = models.ForeignKey(
        AgentRun,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='ai_usage_logs'
    )
    ai_model = models.CharField(max_length=100)
    prompt_tokens = models.IntegerField(default=0)
    completion_tokens = models.IntegerField(default=0)
    total_tokens = models.IntegerField(default=0)
    user_prompt = models.TextField(blank=True)
    response_size_chars = models.IntegerField(default=0)
    success = models.BooleanField(default=True)
    error_message = models.TextField(blank=True, null=True)
    is_billable = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ['-timestamp']
        indexes = [
            models.Index(fields=['organization', 'timestamp']),
            models.Index(fields=['service', 'timestamp']),
        ]

    def __str__(self):
        return f"AIUsage {self.id}: {self.ai_model} - {self.total_tokens} tokens"

    def save(self, *args, **kwargs):
        self.total_tokens = self.prompt_tokens + self.completion_tokens
        super().save(*args, **kwargs)
